require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/screen_shows", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ScreenShow. As you add validations to ScreenShow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ScreenShowsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      ScreenShow.create! valid_attributes
      get screen_shows_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      screen_show = ScreenShow.create! valid_attributes
      get screen_show_url(screen_show), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ScreenShow" do
        expect {
          post screen_shows_url,
               params: { screen_show: valid_attributes }, headers: valid_headers, as: :json
        }.to change(ScreenShow, :count).by(1)
      end

      it "renders a JSON response with the new screen_show" do
        post screen_shows_url,
             params: { screen_show: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ScreenShow" do
        expect {
          post screen_shows_url,
               params: { screen_show: invalid_attributes }, as: :json
        }.to change(ScreenShow, :count).by(0)
      end

      it "renders a JSON response with errors for the new screen_show" do
        post screen_shows_url,
             params: { screen_show: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested screen_show" do
        screen_show = ScreenShow.create! valid_attributes
        patch screen_show_url(screen_show),
              params: { screen_show: new_attributes }, headers: valid_headers, as: :json
        screen_show.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the screen_show" do
        screen_show = ScreenShow.create! valid_attributes
        patch screen_show_url(screen_show),
              params: { screen_show: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the screen_show" do
        screen_show = ScreenShow.create! valid_attributes
        patch screen_show_url(screen_show),
              params: { screen_show: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested screen_show" do
      screen_show = ScreenShow.create! valid_attributes
      expect {
        delete screen_show_url(screen_show), headers: valid_headers, as: :json
      }.to change(ScreenShow, :count).by(-1)
    end
  end
end
